### ISSUE TITLE
Can't View Entire Circle at Full Size

### ISSUE THREAD

**Issue by Zian** [blackhole12/PonyClicker#103]
I'm thankful that it's now possible to "Show Partial Circle" and "Show Entire Circle". Unfortunately, that leaves me without a way to see the details of each pony except for the ones that the website picks for "Show Partial Circle".

Please make it possible to zoom in and pan on the circle.

I've attached 2 screenshots; one showing the entire circle and the other showing the partial circle. Ignore the smile counters; I fiddled with the variables to quickly reproduce the problem.
![partial](https://cloud.githubusercontent.com/assets/1581929/20656135/4d70b2f0-b4de-11e6-85a7-53ef40751f32.png)
![full](https://cloud.githubusercontent.com/assets/1581929/20656136/4d8a215e-b4de-11e6-8021-fcbb1de84083.png)

**Comment by blackhole12** [comment]
If you click and hold (or swipe if you are on a tablet), you can rotate the wheel. You are intended to use this on the partial circle to get to the pony you want.
