### ISSUE TITLE
Wondering if you are interested in having a comic style font for the game interface

### ISSUE THREAD

**Issue by wzx1996** [blackhole12/PonyClicker#106]
Might be a little bit self-promoting, but when I tried injecting my own font "[Comic FlameRat](http://flamerat-yehlon.deviantart.com/art/Font-Comic-FlameRat-691113887)" to the page by injecting a global CSS rule, turns out, it feels kinda okay, and might be a bit better than the browser's default font, though very subjective.

So, wanna ask if you want to have my font in the game. Currently, only having something like
`*{font-family:"Comic FlameRat" !important;line-height:1.3em}`
yields a pretty imperfect result (my font is too "fat", comparing to conventional fonts), but I can fine-tune the CSS to make it look nicer, and also making the missing glyphs (× and ¼, for example).

My font isn't completely free-licensed, but since I own the copyright, I can just allow the use of it in this game without much issue (with a permission similar to those pony SVGs). And, yes, I did search for free licensed comic fonts and there are several results, and if you find those more suitable, I can help tweaking the CSS as well, but I would not be able to add missing glyphs to those fonts.

Just want to ask for your opinion about this. If you consider it okay, I would start working on this and send a pull request when it's ready.

**Comment by blackhole12** [comment]
**No**. Using a weird or unusual font negatively impacts readability. User interfaces should *always* use an easy to read sans-serif font for all body text, and often the rest of the text as well. This would be extremely poor UI design.

**Comment by wzx1996** [comment]
Not gonna argue about the decision you made, but the reason I find using this font (and other kinds of comic-style font) reasonable is that, this is not an app that needs fast reading, and most paragraphs are pretty short, thus I would consider compromising readability to make the UI look more stylish with font choice something okay to do.
