### ISSUE TITLE
Pinkiepocalypse? 

### ISSUE THREAD

**Issue by Wohlf-craft** [blackhole12/PonyClicker#107]
How do you solve this? I had to go on an old backup to fix it. If told, I could add it to the wiki, or something? I know this is not really an issue but I would like to know how to solve it. I don't know where I could contact people. I tried googling it. It leads me here.

**Comment by blackhole12** [comment]
Clicking on pinkies gives you 110% of the smiles they stole so it's actually beneficial.

**Comment by Wohlf-craft** [comment]
Thanks!
