### ISSUE TITLE
The element factorial function doesn't grow fast enough

### ISSUE THREAD

**Issue by blackhole12** [blackhole12/PonyClicker#12]
2^P explodes too fast in late game and overtakes P!/(P-5)!, so a different combination of exponential functions is needed.

EDIT: The element function is actually P!/5! due to the bug listed below. Also, ponies overrun everything else in the game due to exponential blowup. Alternative exponential functions are needed.

**Comment by Jesin** [comment]
P!/(P-5)! is not even an exponential function at all, it's a quintic polynomial.

P!/(P-5)! = P*(P-1)*(P-2)*(P-3)*(P-4), which is less than P^5 for positive P.

**Comment by baxil** [comment]
The displayed formula is incorrect.  Starting a new game with a bunch of hacked cash and adding ponies while keeping 0 of everything else, the tooltip states:

(@7 ponies) -> Buying one EoH will increase your SPS by 42
= 7 * 6 = 7! / 5!

@8 ponies: +336
= 8 * 7 * 6 = 8! / 5!

@9 ponies: +3024
= 9! / 5!

So it's actually calculating P!/5! and each new Pony purchase multiplies by P, as opposed to multiplying by 2 for National Holiday's 2^P.

**Comment by baxil** [comment]
Though as a comment, if it's really calculating P!/5! + FxB, the FxB term is already totally inconsequential by the time you're able to afford an EoH.

**Comment by blackhole12** [comment]
Baxil is correct. I intended to do P!/(P-5)! but screwed up the function and did P!/5! instead because I'm an idiot. I never noticed my mistake, because if I had done it correctly I would have nuked the usefulness of the building.

I'll need to do a survey of possible replacement exponential functions for late game, preferably something involving friendships.

**Comment by baxil** [comment]
My gut feeling as a player is that P!/5! is actually scaled pretty well for late game.  It grows faster than 2^P but doesn't exponentially outpace it.  It does mean that buying new ponies is a super substantial upgrade, but the price multiplies quickly enough on those that the balance still feels reasonable (assuming you're okay with reaching decillions of smiles within a few hours of gameplay -- that sounds insane for players unfamiliar with the genre, but I'm currently earning several sexquinquagillion $/sec in a late-game playthrough of Adventure Capitalist).

**Comment by blackhole12** [comment]
Closed, rebalancing discussion is now in #28
