### ISSUE TITLE
Pony clicks and buildings owned won't update on loading saved data

### ISSUE THREAD

**Issue by adam434** [blackhole12/PonyClicker#13]
After loading or importing the saved data it shows 0 ponies clicked/0 buildings owned in the menu until I click on a pony/buy a building.

**Comment by blackhole12** [comment]
Woah, that shouldn't happen. What platform is this on?

**Comment by adam434** [comment]
Google Chrome v42.0.2311.152m (64-bit) running on Windows 8.1 Professional

**Comment by blackhole12** [comment]
I am unable to repro this on windows 7, but it sounds like part of the javascript isn't firing for some reason.
