### ISSUE TITLE
Redundant display line in "Friendship" tooltip

### ISSUE THREAD

**Issue by baxil** [blackhole12/PonyClicker#15]
With 5 friendships purchased, no upgrades:

> Each friendship generates 1 smile per second
> Each friendship generates **5 smiles** per second
> 5 friendships generating **25 smiles** per second

The first two lines offer conflicting information. Is the first supposed to be the base formula?

(This is possibly a child bug or related bug to #2.)

**Comment by blackhole12** [comment]
I think this is the result of some special handling that was later made redundant, but I need to double check.
