### ISSUE TITLE
Literally unreachable achievements

### ISSUE THREAD

**Issue by baxil** [blackhole12/PonyClicker#16]
Hacking a save file to explore the upper reaches of the game: the smiles required for many achievements are wildly unbalanced against possible income.  Some also exceed your float range.

Buying your 300th Coronation requires 51 vigintillion smiles. Assuming Muffins are still limited to what is given out for Achievements, per #11, then there's a natural limit of approx. 30 Ponies, as by that time your income scales by ~30x each time the cost of a new Pony scales by ~1000x.  Pony #31 requires 8.5x10^45 smiles, and your income is approx. 10^33 SPS, so your next 30x boost in income requires 10^12 seconds, or about 10,000 years.

Assuming that 30 Ponies and 200 Muffins is a rational upper limit on achievable income (the number of friendships and buildings is inconsequential at that point, as all the exponential growth is based on P), to reach 51 vigintillion smiles requires 10^20 years.

The 300th National Holiday and the 300th EoH both display "Infinity" price.

Related: The final click achievement is 10 million clicks.  At a steady rate of 1 click per second 24 hours a day, that's about 3 years of playtime :|

Save file demonstrating numbers:
> {"upgrades":[1,2,3,4,5,6,7,8,9,10,12,13,14,15,11,16,17,18,19,20,21],"upgradeHash":{"1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"10":10,"11":11,"12":12,"13":13,"14":14,"15":15,"16":16,"17":17,"18":18,"19":19,"20":20,"21":21},"smiles":1.5526933868240775e+64,"totalsmiles":2.1607807004474134e+64,"SPC":7.3562172427368e+37,"SPS":1.5056080940398516e+42,"shiftDown":false,"totalTime":10228500,"clicks":10000000,"achievements":{"1":0,"2":0,"3":1,"4":2,"5":3,"6":4,"7":5,"8":6,"9":7,"10":1,"11":2,"12":3,"13":4,"14":5,"15":6,"16":7,"17":8,"18":9,"19":10,"20":1,"21":2,"22":3,"23":4,"24":5,"25":1,"26":2,"27":3,"28":4,"29":5,"30":1,"31":2,"32":3,"33":4,"34":5,"35":1,"36":2,"37":3,"38":4,"39":5,"40":1,"41":2,"42":3,"43":4,"44":5,"45":1,"46":2,"47":3,"48":4,"49":5,"50":1,"51":2,"52":3,"53":4,"54":5,"55":1,"56":2,"57":3,"58":4,"60":1,"61":2,"62":3,"63":4,"65":1,"66":2,"67":3,"68":4,"69":5,"200":1,"201":1,"202":1},"achievementcount":70,"muffins":226,"achievement_muffins":226,"store":[30,400,299,299,299,299,299,299,299,299,299,299,0],"ponyList":[0,40,42,18,53,46,23,8,9,33,31,7,11,34,14,15,54,32,25,56,26,43,17,36,51,20,27,47,37,50,10,2,5,12,3,44,41,29,55,16,48,28,24,45,39,1,22,35,6,13,52,19,57,30,49,4,38,21],"version":3,"settings":{"useCanvas":false,"optimizeFocus":true,"closingWarn":false},"delta":50.03590573766269}

**Comment by blackhole12** [comment]
Sadly, I wrote those achievements before balancing the game, so some of them are now impossible.

I'm really tempted to keep the 10 million clicks one, though.

**Comment by blackhole12** [comment]
This was partially addressed in v0.84. I nerfed all store upgrades to 1, 50, 100, 150, 200, and nerfed the elements even more. I have no idea if these numbers are attainable though.

**Comment by blackhole12** [comment]
This was partially addressed, merging with #30
