### ISSUE TITLE
Scrolling past game area

### ISSUE THREAD

**Issue by loudaslife** [blackhole12/PonyClicker#19]
Clicking (or clicking and holding) the scroll wheel button allows you to scroll past the game area into a blank space. Scrolling by just moving the scroll wheel normally does not have this issue. Seen on Firefox 37.

![bug](https://cloud.githubusercontent.com/assets/7320392/7646419/eb2a590e-fa88-11e4-960d-4170166c299c.png)

Related: The left sidebar extends 8 pixels past the bottom of the game area and is partially cut off when viewed normally.

Sort of related: Is there a way to make the right scroll-bar hidden when playing at a resolution high enough that it's disabled anyway? Grayed out scroll-bars are an eyesore.

**Comment by blackhole12** [comment]
The blank space below was solved with an overflow:hidden on the ponyboard element. The left sidebar issue is likely the goddamn box model being stupid again.

I actually had the scrollbar on auto on the right, then made it permanent after it started causing problems. I'll try putting it back in.

**Comment by blackhole12** [comment]
This was fixed, but you need to do ctrl-F5 if you want the new CSS to show up, otherwise it'll be cached.

**Comment by loudaslife** [comment]
Awesome, it all looks great on my end! Thanks.
