### ISSUE TITLE
Tooltip displays wrong value

### ISSUE THREAD

**Issue by blackhole12** [blackhole12/PonyClicker#2]
The wrong arguments are being passed to CalcSPS() in the tooltip box, and it returns the total SPS instead of the building's individual SPS. Fix by factoring out SPS array and then grabbing the correct SPS from that for the tooltip display.

**Comment by loudaslife** [comment]
I have no idea if this is the same bug, but as of v0.84 tooltip values are pretty borked. The only thing I did between taking the 2 screenshots below was buying and then selling a Friendship in order to update the tooltip values. "172" and "621.461 million" are pretty different values. This happens with every building.

![002af185a9](https://cloud.githubusercontent.com/assets/7320392/7647257/10c8ca20-fa97-11e4-80d9-a89aa0f2ddd5.jpg)
![d3180a8288](https://cloud.githubusercontent.com/assets/7320392/7647258/10ccf46a-fa97-11e4-9e01-1479eb22a3bc.jpg)

**Comment by blackhole12** [comment]
Those values are actually correct, given the information in the tooltip. The cost per +1 increase in SPS is calculated via: (increase in SPS) divided by (cost of building).

The craziness here seems to revolve around how much the friendship is increasing your SPS. In the first one, it was by 63 quintillion, but in the second it was only 17 trillion. If you can post a save game that replicates this I can investigate.

**Comment by loudaslife** [comment]
What I was pointing out was that I got different sets of values even with the exact same circumstances. I only bought and sold the friendship to update the tool-tip values, I own 182 friendships in both picture. I can do the same thing with any building tool-tip when this happens. No idea what causes it, but I randomly see it when checking on my buildings every few minutes.

**Comment by loudaslife** [comment]
I figured out what causes it. For some reason this happens right after I get a new achievement.

**Comment by blackhole12** [comment]
I am currently trying to repro this issue, I'll let you know if I catch it in action

**Comment by blackhole12** [comment]
Successfully repro'd the issue: After getting an achievement, the SPS increase is wrong for some reason.

**Comment by blackhole12** [comment]
When you got an achievement, this could increase your muffin count, which in turn could increase your SPS if you have the right upgrades, but the achievement never triggered a recalculation of the SPS, so it wasn't reflected until you did something else that did (like buy something). I will mark this as fixed and closed once the commit is made, but please verify on your side that it is actually fixed.

**Comment by loudaslife** [comment]
As far as I can tell it's totally fixed in v0.85. I'll update this if I ever see it again.
