### ISSUE TITLE
Inconsistent friendships when ponies added

### ISSUE THREAD

**Issue by latonv** [blackhole12/PonyClicker#22]
Adding a new pony tends to scramble the friendship graph due to the inconsistent order in which friendships are added for increasing pony counts. I think this (untested) modification to the friendship loop in `OrganizePonies()` prevents all those tragic broken friendships:

```javascript
// ponyclicker.html line 997 ...
var f = Game.store[1];
var p1 = 0;
var p2 = 1;
for(var i = 0; i < f; ++i) {
    var x1 = Math.cos(a*p1 + th)*r + r;
    // etc. (x,y calcs and line drawing all identical)
    p1 += 1;
    if(p1 >= p2) { p1=0; p2+=1; }
}
// ...
```

**Comment by blackhole12** [comment]
This was originally how friendships were drawn, but if they are done like this, one pony becomes friends with everypony else, then the next pony does, then the next one, etc. I chose an alternative method to try and randomize the friendship lines in a predictable way, at the cost of breaking friendships when new ponies were added. It can be proven that the method above is the only way to preserve friendships without maintaining an entire adjacency matrix, so it's a matter of choice.

**Comment by latonv** [comment]
Fair enough, I admit it is rather sad having everypony shun pony m until ponies 0 through m-1 finish building a complete graph amongst themselves. I guess the earlier variety in your method does make it slightly more bearable to watch the heart-rending tragedy of all those friendships disappearing. :<

**Comment by blackhole12** [comment]
This is being rejected in favor of a long-term friendship remembering scheme: #37
