### ISSUE TITLE
Incorrect Achievements count, unreachable achievement(s)

### ISSUE THREAD

**Issue by baxil** [blackhole12/PonyClicker#23]
1) The top of the Achievements bar in the menu counts up to 78, but there are 77 active achievement slots.

2) Achievement id 205 (Sell a Friendship) is unattainable, as there is no mechanism for selling purchases. 
As such, achievement id 255 (for unlocking all other achievements) is also unattainable.

**Comment by baxil** [comment]
Update: achievement id 255 also appears bugged.  I assembled a save file with 75/77 achievements active, including 205 but not including 203 or 255, and then fulfilled 203 in-game.  255 did not unlock.

> {"upgrades":[1,7,2,8,3,4,12,9,13,14,16,17,18,19,21,5,6,10,11,15,20],"upgradeHash":{"1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"10":10,"11":11,"12":12,"13":13,"14":14,"15":15,"16":16,"17":17,"18":18,"19":19,"20":20,"21":21},"smiles":1.0838788345028964e+85,"totalsmiles":2.0263962820799206e+86,"SPC":3.7101251721102546e+74,"SPS":1.9095894250808463e+83,"shiftDown":false,"totalTime":3152000,"clicks":100000000,"achievements":{"1":0,"2":0,"3":1,"4":2,"5":3,"6":4,"7":5,"8":6,"9":7,"10":1,"11":2,"12":3,"13":4,"14":5,"15":6,"16":7,"17":8,"18":9,"19":10,"20":1,"21":2,"22":3,"23":4,"24":5,"25":1,"26":2,"27":3,"28":4,"29":5,"30":1,"31":2,"32":3,"33":4,"34":5,"35":1,"36":2,"37":3,"38":4,"39":5,"40":1,"41":2,"42":3,"43":4,"44":5,"45":1,"46":2,"47":3,"48":4,"49":5,"50":1,"51":2,"52":3,"53":4,"54":5,"55":1,"56":2,"57":3,"58":4,"59":5,"60":1,"61":2,"62":3,"63":4,"64":5,"65":1,"66":2,"67":3,"68":4,"69":5,"70":6,"200":1,"201":1,"202":1,"204":1,"205":1},"achievementcount":75,"muffins":1000242,"achievement_muffins":1000242,"store":[39,739,300,300,300,300,300,522,453,403,350,308,0],"ponyList":[41,42,40,56,46,5,4,9,29,44,51,0,35,43,45,50,13,19,57,24,26,2,33,28,16,52,23,22,21,54,27,25,20,47,32,39,31,15,49,1,6,48,11,7,17,14,53,55,36,30,34,38,18,8,10,12,3,37],"version":3,"settings":{"useCanvas":false,"optimizeFocus":true,"closingWarn":true},"delta":33.03200006484985}

**Comment by blackhole12** [comment]
Actually, you can right click to sell something, this feature simply isn't mentioned anywhere. I haven't decided where to expose it yet. You can also shift-click to buy or sell 10 of something at a time.

The achievement for getting all achievements is probably me miscounting the achievement number. I should instead by incrementing achievementCount by Object.keys(achievementList).length, which prevents this error. I'll have to verify this later.
