### ISSUE TITLE
Timer stops when tab isn't visible

### ISSUE THREAD

**Issue by blackhole12** [blackhole12/PonyClicker#24]
The timer is keyed off animation frames, which don't fire when the window isn't visible, so the timer stops. Need to use a setTimeout() function instead. This applies to almost everything that keys off the animation frames.

**Comment by cburschka** [comment]
Maybe a silly question, but couldn't the regular function simply add the full time step instead of only adding exactly .5s?

This would also be more accurate with a low frame rate, where the current code loses up to 1s/FPS per interval...

```diff
    if((timestamp - lastTick)>500) {
-     Game.totalTime += 500;
+     Game.totalTime += (timestamp - lastTick);
      stat_time.innerHTML = displayTime(Game.totalTime);
      UpdateOverlay(null, null);
      lastTick = timestamp;
    }
```

**Comment by blackhole12** [comment]
Note: This fixes the timer issue, but not the fact that when the tab isn't visible, the game just stops completely, which means saving won't happen.
