### ISSUE TITLE
Endgame ideas (Pinkiepocalypse)

### ISSUE THREAD

**Issue by blackhole12** [blackhole12/PonyClicker#27]
Similar to the grandmapacolypse in cookie clicker, RuponyKenshin suggested a "mirror pool pinkie" endgame, where pinkies start overtaking everything and potentially sapping the SPS counter. This could potentially be triggered by buying a "Mirror pool" upgrade, which doubles the value of all friendships or something similar.

This could only be implemented after the late game is better stabilized, but would be nice to have. Also may require more art.

**Comment by loudaslife** [comment]
This is a fantastic idea, especially if someone can make an animation of the fake pinkies exploding.

**Comment by TricksterWolf** [comment]
Another idea: a series of challenges from the show against major villains.  For one possible example, villains may cut friendships or create enemyships to replace them, which requires friendship maintenance.

Also, when you said mirroracolypse, I was all but certain you meant the Torrid Equestria (my name for the alt) disaster caused by Celestia from the comics which actually nearly destroyed all of Equestria.

**Comment by TricksterWolf** [comment]
Based on my earlier confusion, I think Pinkocalypse would make much more sense as a name for it.  It's not the mirror pool as much as it is the presence of portentious pronking pink ponies predicting perfectly posterior paucity of ponykind.

**Comment by blackhole12** [comment]
My current idea for implementing the Pinkiepocalypse is that, after purchasing the mirror pool upgrade, small desktop pinkies start appearing on the screen at a given rate (which could increase if you keep buying mirror-pool related upgrades). Each onscreen pinkie leeches the SPS counter by 1%, applied one after another (the first pinkie leeches 1% of 100% of the SPS counter, the second pinkie leaches 1% of the remaining 99% of the SPS counter, etc.) which prevents 100 pinkies from leeching 100% of the SPS counter. When clicked, a pinkie will explode and return to the mirror pool, yielding 101% of the smiles it leeched.

A second upgrade called "Fully Automatic Unicorn" summons a desktop Twilight Sparkle that walks around and shoots pinkies for you with her magic, sending them back to the mirror pool. This upgrade could also have multiple levels, so you can deal with increasing numbers of pinkies attempting to flood the screen.

**Comment by TricksterWolf** [comment]
(Pinkmenapocalypse kinda flows better...)  :pinkiecrazy:

On Wed, May 20, 2015 at 4:41 PM, Erik McClure <notifications@github.com>
wrote:

> My current idea for implementing the Pinkiepocalypse is that, after
> purchasing the mirror pool upgrade, small desktop pinkies start appearing
> on the screen at a given rate (which could increase if you keep buying
> mirror-pool related upgrades). Each onscreen pinkie leeches the SPS counter
> by 1%, applied one after another (the first pinkie leeches 1% of 100% of
> the SPS counter, the second pinkie leaches 1% of the remaining 99% of the
> SPS counter, etc.) which prevents 100 pinkies from leeching 100% of the SPS
> counter. When clicked, a pinkie will explode and return to the mirror pool,
> yielding 101% of the smiles it leeched.
>
> A second upgrade called "Fully Automatic Unicorn" summons a desktop
> Twilight Sparkle that walks around and shoots pinkies for you with her
> magic, sending them back to the mirror pool. This upgrade could also have
> multiple levels, so you can deal with increasing numbers of pinkies
> attempting to flood the screen.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/blackhole12/PonyClicker/issues/27#issuecomment-104031999>
> .
>



-- 
Trick Question

**Comment by blackhole12** [comment]
Suggestion: There is a 1% chance of all the pinkies being flash sentries instead.
