### ISSUE TITLE
Night Glider's SVG slightly broken

### ISSUE THREAD

**Issue by DJDavid98** [blackhole12/PonyClicker#29]
![Missing stroke on mane top & left eyelashes](http://i.imgur.com/SK1VoTv.png)
_Missing stroke on mane top & left eyelashes_

I have a replacement image of my own [here](http://djdavid98.deviantart.com/art/Flying-Night-Glider-1-S05E02-525626012) but I did not want to submit a pull request straight away because a) it could look like self-advertising and b) it's a different pose

I also reported the issue to the image creator in the comments under the current image, but in the meantime you might want to temporarily/permanently change the image to either the one I linked or just  a different one in general.

**Comment by blackhole12** [comment]
I had to have someone point out that she was missing an outline on top before I noticed XD.

I like your image better, anyway. Be sure to change the credits when you do, though. Also, I still have to merge your gigantic changelist with master, so be careful about making a pull request because there may be merge conflicts.

**Comment by DJDavid98** [comment]
If I posh anything else right now, it'll be added to that pull request, so if you need them separate, I'll wait for your merge.

**Comment by blackhole12** [comment]
Alright, It'll be ~3 hours until I leave work for the weekend, at which point i'll start trying to merge.

**Comment by Jesin** [comment]
Your vectors all appear to be pretty high-quality. I think https://djdavid98.deviantart.com/art/Flying-Night-Glider-2-S05E02-525820590 is a more interesting pose but there's no SVG. It'd be great if you could contribute more SVG files.

**Comment by DJDavid98** [comment]
If needed I can export any of my current images as SVGs, will do that now for that image as well.

**Comment by loudaslife** [comment]
This reminds me, [Dinky Doo's right eye is borked](https://github.com/blackhole12/PonyClicker/blob/master/ponies/Dinky%20Doo.svg). The preview image on [ZuTheSkunk's deviant art post](https://zutheskunk.deviantart.com/art/MLP-Resource-Dinky-Hooves-01-212564935) looks correct, but if I download the SVG linked in said post her eye is once again broken. This may be an issue with browser rendering, as all of the images look correct when viewed in Inkscape.

![386c5a0972](https://cloud.githubusercontent.com/assets/7320392/7664217/2297c5c4-fb43-11e4-8148-2a15fd67addc.png)

**Comment by DJDavid98** [comment]
@loudaslife That issue will be corrected along with Night Glider's when I'm done with #36

I'm going through all the images while making sure they display properly.

**Comment by blackhole12** [comment]
Blueblood's SVG was not squarified, so he looks partially cut off when resized.

![bluebloodbug](https://cloud.githubusercontent.com/assets/3387013/7665188/421ea8c2-fb61-11e4-9df9-1cb68c816778.png)

**Comment by blackhole12** [comment]
This has been merged and vetted.

**Comment by blackhole12** [comment]
Nightglider's SVG has been re-broken because the new one was not squarified. I can't do this myself, because inkscape will add a bunch of crap to the SVG file, and manually editing the viewbox puts all the whitespace to the right instead of centering the image.

**Comment by DJDavid98** [comment]
I did this manually suing the formula `offset = (biggerside - smallerside)/2` then apply the offset to the smaller side's `0` while multiplying it by `-1`, so it this case `offset = (2149.5 - 1573.3)/2 = 288.1`, so viewBox changes from `0 0 1573.3 2149.5` to `-288.1 0 2149.5 2149.5`. I'll push the fix ASAP.
