### ISSUE TITLE
Add update detector

### ISSUE THREAD

**Issue by blackhole12** [blackhole12/PonyClicker#31]
Ponyclicker should have a check every 5 minutes or so that uses an AJAX request to download CHANGELOG.md and grabs the first version listed in it. If the version is greater than the version it was compiled with, it should display a notice telling the user to refresh the page. Clicking the refresh link should 1) save the game and 2) disable a page reload check.

**Comment by ngyikp** [comment]
Ehh... Can't this be done with a JSON file that contains only

```json
{"version": 1.0}
```

instead of parsing ```CHANGELOG.md``` that would be fragile/problematic?

**Comment by blackhole12** [comment]
Well, if you want to have three places you have to remember to increment the version instead of just two, yes. However, I have to point out that **you cannot encode the version as a number**. A version does not obey decimals, because v1.1 < v1.10, so it must actually be a string. If you want to maintain a JSON file you might as well make it {"major":1,"minor":0} so a proper check can be done. Maybe stick in a revision number there too, just in case.

**Comment by blackhole12** [comment]
It turns out that we need to add ?v=0.86 to our CSS and JS file requests (and anything else we want to bypass the cache), so we're going to end up with the version number in 10 different places anyway. Some of this can be alleviated via javascript, but the CSS request can't because it's in the <HEAD> request. So i'm just going to do this via JSON file.
