### ISSUE TITLE
The ladder in getNews() contains unreachable code.

### ISSUE THREAD

**Issue by TricksterWolf** [blackhole12/PonyClicker#33]
The getNews() selections in the if-else-if ladder with constants 1000000000 or larger fail to run.  I presume this in an issue with badly-formed integer constants, or how the smile information is saved.

**Comment by blackhole12** [comment]
I cannot repro this in the current version of pony clicker. Setting alerts() and manually setting muffin counts confirm that in Chrome, these code sections are in fact run. Was this in firefox?

**Comment by TricksterWolf** [comment]
It was in Chrome.  I noticed I was never getting those messages, so I
presume for some reason they were never pushed.

On Wed, May 20, 2015 at 9:12 PM, Erik McClure <notifications@github.com>
wrote:

> I cannot repro this in the current version of pony clicker. Setting
> alerts() and manually setting muffin counts confirm that in Chrome, these
> code sections are in fact run. Was this in firefox?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/blackhole12/PonyClicker/issues/33#issuecomment-104086591>
> .
>



-- 
Trick Question

**Comment by blackhole12** [comment]
Keep in mind, those aren't minimum values, they are ranges - your smile amount must be between 1000000000 and 1000000000000 to get the "Princess Twilight found overdosed on friendship, taken to rehab center!" message. This is on purpose, because those messages are supposed to reflect your current smile amount. If you have a gajillion smiles, you won't get those messages anymore.

**Comment by TricksterWolf** [comment]
Ah, I see.  I don't remember having seen them at all, but it's possible
those ranges just went by too quickly for me.

It's probably fine.


On Wed, May 20, 2015 at 9:26 PM, Erik McClure <notifications@github.com>
wrote:

> Keep in mind, those aren't minimum values, they are ranges - your smile
> amount must be between 1000000000 and 1000000000000 to get the "Princess
> Twilight found overdosed on friendship, taken to rehab center!" message.
> This is on purpose, because those messages are supposed to reflect your
> current smile amount. If you have a gajillion smiles, you won't get those
> messages anymore.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/blackhole12/PonyClicker/issues/33#issuecomment-104089845>
> .
>



-- 
Trick Question

**Comment by blackhole12** [comment]
Closed, no repro.
