### ISSUE TITLE
Order of upgrade purchase influences final result inaccurately.

### ISSUE THREAD

**Issue by TricksterWolf** [blackhole12/PonyClicker#34]
The upgrade purchase order influences the final result.  This generally results in clicking becoming completely useless after half of the muffin upgrades are complete (unless you save the click upgrades to last, which I have confirmed here).

The upgrades need to be divided into three pools and calculated in the following order:
0) everything that doesn't mention % (also, any non-upgrade calculations go here)
1) muffin % upgrades
2) click % upgrades

**Comment by blackhole12** [comment]
Pool 0 has to be further subdivided into per-building SPS % increases, and then subdivided between additions coming first and multiplications coming afterwards. I'd like to come up with a neater way of expressing this in the upgrade functions using some sort of pure functional method.

**Comment by TricksterWolf** [comment]
Well, the clicking is straightforward: just set it to whatever the total percentage is.  If you purchase it last it's worth 10% in full.  The two numeric increases for clicking aren't really compatible with the long run game.  At present you can remove SPC entirely once the first 1% is purchased, as it's essentially the same thing.

As for the rest of it, I think it would be better to wait until reimagining the pony-to-friendship system happens.  Everything needs to change if ponies go up in number: the exponential and factorial building calculations need to go away--they belong in the enhancements area instead since those can be limited in number (i.e., "enhancement: each blah produces twice as much").
