### ISSUE TITLE
SVG optimization & correction

### ISSUE THREAD

**Issue by DJDavid98** [blackhole12/PonyClicker#36]
The current SVGs have loads of unnecessary white space & Inkscape/Illustrator metadata that can be safely eliminated without damaging the image itself.

Some used vectors also have colors that are different from the [MLP-VectorClub](http://mlp-vectorclub.deviantart.com/) [vector color guide](http://i4.minus.com/iurGZ8Q9WHQVp.png), and a few vector files are broken, both of which will be corrected.

I'll do this myself, I just wanted to have an issue that I can reference later in the commit.

**Comment by blackhole12** [comment]
Just to clarify, you aren't going to be removing the white space on the sides of the SVGs, right? They were all set to be perfect squares on purpose (which took like 10 minutes of very boring manual labor), because otherwise they'll get stretched in the pony wheel.

**Comment by DJDavid98** [comment]
White space as in the SVG source. Durin this operation the appearance of the images do not change, only the file size decreases.

**Comment by blackhole12** [comment]
In that case, awesome.

**Comment by blackhole12** [comment]
This has been merged and vetted.
