### ISSUE TITLE
Should clicks be renamed to boops?

### ISSUE THREAD

**Issue by blackhole12** [blackhole12/PonyClicker#38]
While the game is called Pony Clicker as a homage to Cookie Clicker, it might make more sense to refer to clicking as "booping" in-game, which has a much more direct connection to "generating smiles".

**Comment by TricksterWolf** [comment]
I think the game should be called Pony Clicker, but "boop" is much better than click.  I'd use "boop" everywhere except the name of the game.

**Comment by TricksterWolf** [comment]
Related to both this and the suggestion for a "fast booping" achievement:  http://derpy.me/boop

**Comment by Jesin** [comment]
I like this suggestion.

**Comment by DJDavid98** [comment]
+1

**Comment by cburschka** [comment]
I'd also agree with naming it "boop" in the game (achievements, "smiles per boop" etc.) but leaving the name as it is.

**Comment by ILM126** [comment]
I like the idea. Would it be possible if a click rate achievement was added, like 5 clicks/second or 7. If that's possible...
