### ISSUE TITLE
New character image suggestions

### ISSUE THREAD

**Issue by DJDavid98** [blackhole12/PonyClicker#48]
I personally think that the images currently in place for the ponies listed below could be substitued for better alternatives. Here are my suggestions:

### Fluttershy
[![](http://th09.deviantart.net/fs71/200H/f/2014/077/d/1/happy_fluttershy_by_givralix-d79nykv.png)](http://givralix.deviantart.com/art/Happy-Fluttershy-439497679 "#1") [![](http://th06.deviantart.net/fs70/200H/f/2014/058/3/4/another_fluttershy_vector_by_vladimirmacholzraum-d78693x.png)](http://vladimirmacholzraum.deviantart.com/art/Another-Fluttershy-Vector-436991901 "#2")

### Lightning Dust
[![](http://th00.deviantart.net/fs70/200H/i/2014/036/5/c/lightning_dust_by_kiowa213-d6mgx93.png)](http://kiowa213.deviantart.com/art/Lightning-Dust-400538199 "#1") [![](http://th06.deviantart.net/fs70/200H/i/2013/228/8/0/standing_lightning_dust_by_hankofficer-d6ida85.png)](http://hankofficer.deviantart.com/art/Standing-Lightning-Dust-393649925 "#2")

### Starlight Glimmer
[![](http://t15.deviantart.net/vDBiCrQ-4Ae_G3F2KDIW5HStFv0=/300x200/filters:fixed_height(100,100):origin()/pre03/79c0/th/pre/i/2015/097/8/c/element_of_charisma_by_reginault-d8otza4.png)](http://reginault.deviantart.com/art/Element-of-Charisma-525438940 "#1") [![](http://t13.deviantart.net/IYWqKlrQoiAw7uIn-RvA2ChrtK0=/300x200/filters:fixed_height(100,100):origin()/pre05/fdf6/th/pre/f/2015/097/2/4/proud_starlight_glimmer__s05e01__by_djdavid98-d8kq5lz.png)](http://djdavid98.deviantart.com/art/Proud-Starlight-Glimmer-S05E01-518542055 "#2")

### Rainbow Dash
[![](http://th09.deviantart.net/fs71/200H/i/2012/190/6/1/rainbow_dash_2_by_xpesifeindx-d56mlm3.png)](http://xpesifeindx.deviantart.com/art/Rainbow-Dash-2-313463019 "#1") [![](http://th09.deviantart.net/fs70/200H/f/2014/143/6/0/rainbow_smile_by_starshinecelestalis-d7jddse.png)](http://starshinecelestalis.deviantart.com/art/Rainbow-Smile-455800334 "#2") [![](http://th05.deviantart.net/fs70/200H/i/2014/285/5/4/adashable__3_by_geometrymathalgebra-d81xghx.png)](http://geometrymathalgebra.deviantart.com/art/Adashable-3-486970053 "#3")

**Comment by blackhole12** [comment]
I vote right, left, right, rightmost, in that order, IMO.
