### ISSUE TITLE
Different "Pony vectors by" formatting

### ISSUE THREAD

**Issue by DJDavid98** [blackhole12/PonyClicker#53]
In #48 @blackhole12 has chosen another image of mine, as a replacement for Starlight Glimmer, however, I think it'd look cluttered in the list if I wrote my name again, like it's already been done with 90Sigma's name.

Because of this, I propose the following syntax:

> [Name1](/link), [Name2](/link), Name3 ([1](/link), [2](/link)), [Name4](/link), Name5 ([1](/link), [2](/link), [3](/link)), [Name6](/link) ...

What do you think?

**Comment by blackhole12** [comment]
Sure, although i think the name should be a link to their deviantart page if they have multiple contributions.

**Comment by DJDavid98** [comment]
I'll do that then when I'm adding the new images.
