### ISSUE TITLE
Add Vinyl Scratch/DJ P0N-3

### ISSUE THREAD

**Issue by DJDavid98** [blackhole12/PonyClicker#57]
I suggest adding Vinyl to the list of ponies. Below are the two vectors I found that look suitable. The [rest](http://mlp-vectorclub.deviantart.com/gallery/36303771/Minor-DJ-P0N-3-aka-Vinyl-Scratch) didn't seem to fit. There was [this](http://nightflyer22.deviantart.com/art/DJ-Vinyl-Scratch-Vector-527607352) one as well but it has no svg.
<br>
<a href="http://fav.me/d72dawc"><img src="http://th05.deviantart.net/fs71/200H/f/2014/291/b/5/dj_pon3_by_skie_vinyl-d72dawc.png"></a>  <a href="http://fav.me/d8hu9a8"><img src="http://th03.deviantart.net/fs71/200H/f/2015/044/0/b/vinyl_scratch____beautiful___by_djdavid98-d8hu9a8.png"></a>

**Comment by blackhole12** [comment]
The left seems most suitable (and also avoids the fandom argument about her eye color).
