### ISSUE TITLE
Idea: Add an "affordable in: ---" countdown for stuff

### ISSUE THREAD

**Issue by cburschka** [blackhole12/PonyClicker#60]
The "A will pay off in X seconds" number in the tooltip is a very useful statistic, mostly because you can decide whether buying A will get you to B faster.

The other useful number for that is "B can be purchased in Y seconds" based on the current rate (because A will be worth it if X < Y).

It could just be a clock next to the price on the button, or something...

**Comment by cburschka** [comment]
This is what it looks like:

![screenshot from 2015-05-17 13 39 17](https://cloud.githubusercontent.com/assets/1448001/7670159/264f4cac-fc9a-11e4-8965-5ac1ff28f7ad.png)

I went with 100 years as the maximum that is still displayed (anything beyond that is "Centuries", though I guess technically that label isn't completely accurate for 100-200 years :P ). This is a bit much, but it's still neat to see a rate boost drop something from "75 years" to "7 years" or something.

**Comment by blackhole12** [comment]
A counter that says "B can be purchased in X seconds" may cause problems because it can only key off of the SPS, and so would jump literally every time you clicked a pony or when an event modifies the SPS (such as clicking on a desktop pony after those are implemented). Regardless, this needs to be in the tooltip, not in the price table itself.

I'm not sure I quite follow what "A will pay off in X seconds" means. What calculation would that be?

**Comment by cburschka** [comment]
That's the "You pay X smiles per +1 SPS" that's currently in the tooltip.

**Comment by cburschka** [comment]
And yeah, the counter of course only reflects the current SPS - it only counts down normally as long as you're not doing anything, and otherwise changes in unpredictable ways. You can go ahead and try it out though (see [issue-60](/cburschka/PonyClicker/tree/issue-60)). I think the UI looks kind of neat, especially because unlike the tooltip, you can watch this timer ticking down.

Of course, this could be an optional thing that can be turned on with a checkbox...

**Comment by blackhole12** [comment]
An overlay-only version of this has been spliced into the main Pony Clicker code. Some time in the future, a checkbox could be used to enable a timer on the cost.
