### ISSUE TITLE
Shift+rightclick opens browser rightclick menu

### ISSUE THREAD

**Issue by Sorunome** [blackhole12/PonyClicker#62]
When trying to sell 10 in the store, using shift+rightclick opens the browsers rightclick menu.

Tested in Firefox.

**Comment by cburschka** [comment]
This is by design; Firefox does not allow the shift right-click to be intercepted by javascript, to give users a reliable way of getting to the context menu.

I suppose that if you want bulk selling on right click, you would have to use some other modifier key - perhaps Control.

**Comment by blackhole12** [comment]
Ctrl has been tested and works, but I really wanted shift :C

**Comment by Sorunome** [comment]
you could bind to both key combinations, though allowing the user to chose whichever he/she wants to do
