### ISSUE TITLE
Allow viewing entire pony circle

### ISSUE THREAD

**Issue by blackhole12** [blackhole12/PonyClicker#71]
Even though the ponies become so small you can't click on them effectively, people liked looking at the geometric shapes created from the circle. We should add a checkbox that tries to shove the entire pony circle inside your viewing area with no regard to the pony sizes for the sake of viewing it. This could also turn the entire circle into a clickable object.

**Comment by Sorunome** [comment]
For turning the whole circle into a clickable object just bind your click function to the canvas.

**Comment by Abion47** [comment]
Would it be a problem is the entire circle was a clickable object? Anything you click does the same thing anyway.

**Comment by blackhole12** [comment]
Not really, that's why i suggested simply making the entire circle a clickable object. Ideally i'd also want a clicking animation for it, though.
