### ISSUE TITLE
Remove obsolete uses of "SPC"

### ISSUE THREAD

**Issue by baxil** [blackhole12/PonyClicker#72]
When clicking was changed to "booping", it looks like some uses of Smiles Per Click were not updated into Smiles Per Boop (SPB).

"Booping Assistants" upgrade: "Booping gets +1 SPC for each pony you have."
"Friendship is Booping" upgrade: "Booping gets +1 SPC for each friendship you have."

**Comment by cburschka** [comment]
I guess it's enough to change the user-facing text for now (so only the above two), not variable names or comments.
