### ISSUE TITLE
Bug With "Highlight Most Efficient Purchase" Option

### ISSUE THREAD

**Issue by Abion47** [blackhole12/PonyClicker#83]
Sometimes there isn't a purchase that is labelled as most efficient. On one such occasion, I decided to go ahead and buy a pony. Once I did so, Friendship was highlighted. What I believe is happening is that the highlight system is marking Friendship as the most efficient option, but since the number of Friendships were maxed out and the purchase disabled, the highlight was hidden.

**Comment by blackhole12** [comment]
This is because the disabled CSS overrides the highlight. I am unsure if
this is a bug or intended behavior. I kind of like not always giving you
the most efficient purchase, because then you have to think about it.
