### ISSUE TITLE
Images not loading from server

### ISSUE THREAD

**Issue by Pyrii** [blackhole12/PonyClicker#86]
Having trouble loading the game at the moment and the chrome network analyser is showing that it's just the images from the game's server.
![ponynet](https://cloud.githubusercontent.com/assets/932782/7904682/5826f432-07fd-11e5-9fb8-c5f1803bfd0d.png)

**Comment by Pyrii** [comment]
Well it's working again for now, but it does appear to be an intermittent problem.

**Comment by blackhole12** [comment]
I'm really not sure what to do about this. I don't control github's hosting. If github abruptly decides to just stop hosting my files I can't really do much about it.

**Comment by Pyrii** [comment]
Yeah, it's happening again. The problem is the game won't reload if it can't load the images.
![ss 2015-06-03 at 01 12 24](https://cloud.githubusercontent.com/assets/932782/7950081/c2bf654a-098d-11e5-90b4-5207dfa1bd72.jpg)

**Comment by blackhole12** [comment]
I just tried it and the images are loading for me. Are you sure this isn't something to do with your internet?

**Comment by Pyrii** [comment]
Maybe we should look into some external hosting for the images.
