### ISSUE TITLE
Grand Galloping Gala and Coronation prices inverted

### ISSUE THREAD

**Issue by blackhole12** [blackhole12/PonyClicker#9]
The initial prices of the GG and coronation are inverted because of differing SPS. One either needs to be increased or decreased or the SPS needs to be modified.

**Comment by baxil** [comment]
There's a different scaling factor for their prices, so it corrects itself quickly.  If you start a new game with hacked cash and buy 10 of each, the 11th GG costs 261 million and the 11th Coronation costs 346 million.  However, I agree the initial price should be in strictly increasing order.
