### ISSUE TITLE
calculation or thinking error with upgrades?

### ISSUE THREAD

**Issue by 3plus4i** [blackhole12/PonyClicker#90]
I just stumbled over a problem with calculation of the bonuses of Upgrades. A little backstory:
Since the game doesn't calculate the cost ratio of upgrades, I created a spreadsheet to do this on my own, manually. Some of the formulas are rather complex so I wanted to check with an actual example, if I made any mistakes (I already found several of them :sweat_smile: ).

One of the first Upgrades I purchase is the first friendship-upgrade (id:7). Since it says "+1 SPS for **every other friendship**" and I have 38 friendships I should gain 1x38x37=1406 SPS. Actually I got 1444. I don't know a thing about the syntax of JS but shouldn't
`sps.pStore[item] += pSPS*store[item]`
be more something like
`sps.pStore[item] += pSPS*(store[item]-1)`,
since the additional SPS apply for **every other** item?

**Comment by blackhole12** [comment]
This is really just bad wording. It's +1 SPS for every friendship, not every other friendship.

**Comment by 3plus4i** [comment]
Oh, so it's actually supposed to be like that. Then I'd suggest to change the description accordingly. Just deleting the "other" should already be sufficient.

I could try to do this myself, couldn't I? Never worked with submits before. That could be an easy chance to try it out. Would that be useful?

**Comment by blackhole12** [comment]
I am still debating whether to change the wording to "+1 for each friendship" or to change how it's calculated.

**Comment by 3plus4i** [comment]
Well, in the end both versions make sense. Personally I like the "for every other item" more, I think.
