### ISSUE TITLE
OC Ponies?

### ISSUE THREAD

**Issue by 155e55** [blackhole12/PonyClicker#91]
I'm guessing that this has been suggested before, but why not use some OCs for the ponies. I bet lots of people would be willing to let you use their pictures.

**Comment by blackhole12** [comment]
OC ponies won't be part of the basic game, but instead are going to be a feature of the Mod API, as mentioned in #88 v1.1 Planning. That will let you add or replace the ponies with whatever images you want.

**Comment by 155e55** [comment]
ah, ok.
