### ISSUE TITLE
pause function

### ISSUE THREAD

**Issue by 3plus4i** [blackhole12/PonyClicker#93]
Just a very spontaneous idea I just had: Would it be useful to add a button to pause the game? I'm not really sure by myself. The game can get pretty intense and fast at some points, especially between about 2.5 and 3 hours in the game, from my experience (let alone if you have a lot of cupcakes). Sure, it doesn't hurt to just let the game run on but if you're aiming for the best possible result in a minimum of (play) time, a pause function could be helpful, especially with a hotkey (or is it actually a shortcut).

**Comment by BenFreir** [comment]
I've thought about this for a few minutes now, and it might be pretty easy, even if I don't understand why someone would want this;

If there was one Var called "paused" or something, then it could check whether that var is on or off (1 or 0) and either keep adding on points like it was before, or stop adding points to the total, as well as not counting time, amount of clicks, smiles, things like that.

My JS and JQ knowledge is pretty lackluster, but I think it might work if someone better than me went into the files ;3

**Comment by blackhole12** [comment]
This would be trivial to implement but it seems kind of pointless. I mean really, the whole point of the clicker game is to keep you engaged, so if you feel like you need a pause button then the game is doing it's job :P

**Comment by 3plus4i** [comment]
Yeah, that's true. It just seams to me, that it's **to** engaging at some points (mostly between 2.5 and 3 hours of gameplay). It also depends on how you play the game, I think. If you don't care about losing a couple of seconds here and there or not making an optimal purchase from time to time, a pause function is definitely pointless.

Then again, it's walking a thin line with games like these, it seams. Just clicking on random buttons over and over again, without a noteworthy pause, can be pretty exhausting. If you feel pressed to keep up pace and effort to maintain motivation, you may actually lose it quickly. Or is that just me? Sometimes it feels a bit like Lesson Zero to me. Trying to optimize my strategy is pretty much the only thing that keeps me motivated.

Like I said: I'm not really sure by myself, if this is a good idea. Though, on the other hand, it wouldn't really hurt to have it. Might even be worth an achievement, if one uses the pause button, similar to manually saving or exporting/importing ...

**Comment by Abion47** [comment]
I can't think of any possible reason to want or need a pause function. Stepping away for a couple minutes doesn't hurt at all, as smiles are always accumulating whether you are there or not. On the other hand, pausing the game for a couple minutes makes you lose two minutes worth of smiles which strikes me as a very *non*-optimal way of playing.

**Comment by blackhole12** [comment]
Closing. There is no reason to implement a pause button.
