### ISSUE TITLE
EQLA Panel

### ISSUE THREAD

**Issue by blackhole12** [blackhole12/PonyClicker#97]
I am going to be doing a panel about Pony Clicker's development history at [Equestria LA](https://equestriala.com/), and I need to know if anyone who worked on it will be there.

@ReneZeidler, @ngyikp, @torrentails, @pjjmd, @MaxLaumeister, @TricksterWolf, @SonicN, @cburschka, @phytenman, @DJDavid98, @3plus4i, @Akamaru, @BenFreir, @BlackliteWrath, @Brony19, @ConnorMonson, @kazenosaga, @LittleFinix, @yecki, @MartinYAY

If anyone is going to EQLA and would like to be on the panel with me to talk about their contributions, even if it was just an issue submission, **you must send me an e-mail** at erikm [AT] blackspherestudios [DOT] com with your **full name and alias** so I can give it to the EQLA organizers by ***August 13th* at the latest!**

The panel will be taking place on **Sunday September 6, 2015** from **12:45 PM to 1:45 PM**,provided there are no schedule changes.

**Comment by torrentails** [comment]
I wish I could be there, but unfortunately I'm stuck in Australia for the time being.

**Comment by DJDavid98** [comment]
It is too far away, plus I have school by then.

**Comment by cburschka** [comment]
Wrong continent sadly, but I'm excited you get to present this!

**Comment by DJDavid98** [comment]
Would it be possible to get a recording of the event afterwards? I'd love to see it.

**Comment by blackhole12** [comment]
Some panels are routinely recorded at conventions, but I'm not really sure if the Pony Clicker panel is going to be popular enough for an official recording. I'll ask them about it when sending off my finalized information.

**Comment by TricksterWolf** [comment]
I don't think even if I were lucky enough to attend that I'd warrant the
invite, but I appreciate it.  Have fun!  (My current pony project is
working with some ugly C code, yay.)


On Sun, Aug 9, 2015 at 9:24 AM Erik McClure <notifications@github.com>
wrote:

> Some panels are routinely recorded at conventions, but I'm not really sure
> if the Pony Clicker panel is going to be popular enough for an official
> recording. I'll ask them about it when sending off my finalized information.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blackhole12/PonyClicker/issues/97#issuecomment-129187830>
> .
>
-- 

--
Trick Question

**Comment by blackhole12** [comment]
The pony clicker panel was not recorded, sorry guys :C
