### ISSUE TITLE
Trouble with importing saves

### ISSUE THREAD

**Issue by SierraLarson** [blackhole12/PonyClicker#99]
I can't seem to import my save file. I'd love to continue where I left off before, but when I put it in, nothing changes.

My save file/code is: 
{“upgrades”:[1,2,7,3,8,4,5,12,9,6,13,10,14,15,11,16,17,18,19,20,21],“upgradeHash”:{“1”:1,“2”:2,“3”:3,“4”:4,“5”:5,“6”:6,“7”:7,“8”:8,“9”:9,“10”:10,“11”:11,“12”:12,“13”:13,“14”:14,“15”:15,“16”:16,“17”:17,“18”:18,“19”:19,“20”:20,“21”:21},“smiles”:4.9624667071656466e+26,“totalsmiles”:1.7885710640515677e+27,“SPC”:62668670118087130000,“SPS”:2.070557632582351e+23,“shiftDown”:false,“totalTime”:8734000,“clicks”:4187,“achievements”:{“1”:0,“2”:0,“3”:1,“4”:2,“5”:3,“10”:1,“11”:2,“12”:3,“13”:4,“14”:5,“15”:6,“16”:7,“17”:8,“18”:9,“19”:10,“20”:1,“21”:2,“22”:3,“23”:4,“24”:5,“25”:1,“26”:2,“27”:3,“28”:4,“29”:5,“30”:1,“31”:2,“32”:3,“33”:4,“34”:5,“35”:1,“36”:2,“37”:3,“38”:4,“40”:1,“41”:2,“42”:3,“45”:1,“46”:2,“47”:3,“50”:1,“51”:2,“52”:3,“55”:1,“56”:2,“60”:1,“61”:2,“65”:1,“66”:2,“67”:3,“68”:4,“200”:1,“201”:1,“202”:1,“203”:1,“204”:1},“achievementcount”:56,“muffins”:155,“achievement_muffins”:155,“store”:[22,212,255,230,200,170,140,120,100,93,70,63,0],“ponyList”:[0,6,33,2,4,8,24,15,34,49,41,56,51,48,17,27,11,31,44,20,19,40,18,25,36,16,14,22,42,3,12,29,47,13,30,7,35,21,39,32,23,1,46,55,37,9,54,57,45,53,43,28,26,52,10,38,5,50],“version”:3,“settings”:{“useCanvas”:false,“optimizeFocus”:true,“closingWarn”:true},“delta”:15.871999960392714}

I just copied it from the thing before, of course, so I don't see how there could be any errors in it... Unless it's not reading it because the save codes are different now? If that's the case, can anyone make it so that my save works?

**Comment by blackhole12** [comment]
Whatever you pasted the code into apparently changed the raw ascii " into pretty unicode smart quotes: “”. Because of this it can't read it, because they aren't technically quotes, they're special characters. Here is your save file with the quotation marks restored:

```{"upgrades":[1,2,7,3,8,4,5,12,9,6,13,10,14,15,11,16,17,18,19,20,21],"upgradeHash":{"1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"10":10,"11":11,"12":12,"13":13,"14":14,"15":15,"16":16,"17":17,"18":18,"19":19,"20":20,"21":21},"smiles":49624667071656466e+26,"totalsmiles":17885710640515677e+27,"SPC":62668670118087130000,"SPS":2070557632582351e+23,"shiftDown":false,"totalTime":8734000,"clicks":4187,"achievements":{"1":0,"2":0,"3":1,"4":2,"5":3,"10":1,"11":2,"12":3,"13":4,"14":5,"15":6,"16":7,"17":8,"18":9,"19":10,"20":1,"21":2,"22":3,"23":4,"24":5,"25":1,"26":2,"27":3,"28":4,"29":5,"30":1,"31":2,"32":3,"33":4,"34":5,"35":1,"36":2,"37":3,"38":4,"40":1,"41":2,"42":3,"45":1,"46":2,"47":3,"50":1,"51":2,"52":3,"55":1,"56":2,"60":1,"61":2,"65":1,"66":2,"67":3,"68":4,"200":1,"201":1,"202":1,"203":1,"204":1},"achievementcount":56,"muffins":155,"achievement_muffins":155,"store":[22,212,255,230,200,170,140,120,100,93,70,63,0],"ponyList":[0,6,33,2,4,8,24,15,34,49,41,56,51,48,17,27,11,31,44,20,19,40,18,25,36,16,14,22,42,3,12,29,47,13,30,7,35,21,39,32,23,1,46,55,37,9,54,57,45,53,43,28,26,52,10,38,5,50],"version":3,"settings":{"useCanvas":false,"optimizeFocus":true,"closingWarn":true},"delta":15871999960392714}```

To prevent this in the future, try copying and pasting into something really simple, like Notepad, that won't try to be "helpful". I'm classifying this as a bug and will try to write code that catches this and replaces the quotations automatically.

**Comment by blackhole12** [comment]
This has been fixed. Refresh pony clicker and you should be able to import your save file.

**Comment by SierraLarson** [comment]
Thank you so much! It's nice to see my game again.

Now I just need to find another place to store the save without it messing it up.
